version: '3.8'

services:
  web:
    image: ${DOCKER_USERNAME}/vxga-music:latest
    
    expose:
      - "5000"
    volumes:
      - ./tracks:/app/static/music
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s      # Как часто проверять
      timeout: 10s       # Сколько ждать ответа
      retries: 3         # Количество неудачных попыток до статуса "unhealthy"
      start_period: 10s  # Время на прогрев приложения при старте
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      # Путь к конфигу на сервере
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Путь к трекам
      - ./tracks:/usr/share/nginx/html/static/music:ro
    depends_on:
      web:
        condition: service_healthy  # Ждем, пока Flask пройдет хелсчек
    restart: always