server {
    listen 80;
    server_name vxga-music.duckdns.org; # IP (или домен в будущем)

    # Максимальный размер загружаемого файла (чтобы жирные треки не резались)
    client_max_body_size 100M;

    # 1. Раздаем статику (музыку и CSS) силами самого Nginx, минуя Flask
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 2. Все остальные запросы перенаправляем во Flask
    location / {
        proxy_pass http://web:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}