server {
    listen 80;
    server_name vxga-music.duckdns.org;

    client_max_body_size 100M;

    # Раздаем музыку из правильного пути внутри контейнера
    location /static/music/ {
        alias /usr/share/nginx/html/static/music/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Все остальные запросы (включая остальную статику и логику) проксируем во Flask
    location / {
        proxy_pass http://web:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}