---
- name: Deploy Music Portfolio Application
  hosts: all
  become: yes  # Выполнять команды от имени root (sudo)

  tasks:
    - name: Update apt cache and install prerequisites
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create app directory for music files
      file:
        path: /var/www/music_app/tracks
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy docker-compose.yml to server
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/MusicPlatform/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    # Создаем файл .env на сервере и пишем туда логин
    - name: Create .env file for Docker Compose
      lineinfile:
        path: /home/ubuntu/MusicPlatform/.env
        line: "DOCKER_USERNAME={{ docker_hub_username }}"
        create: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600' # Права только для чтения владельцем

    - name: Pull latest images from Docker Hub
      shell:
        cmd: docker compose pull
        chdir: /home/ubuntu/MusicPlatform

    - name: Restart application container
      shell:
        cmd: docker compose up -d --force-recreate
        chdir: /home/ubuntu/MusicPlatform